#!/bin/sh
# Rewrite dist/dhancha.deps from the DECLARED [deps] stdlib in cyrius.cyml.
#
# ⛔ WHY THIS EXISTS — PORTED FROM setu 2026-08-17, AFTER dhancha PAID THE SAME BILL.
# `cyrius distlib` generates `dist/dhancha.deps` and its own header calls it "stdlib leaves this fold
# requires in scope", but its output is neither the declared list nor a symbol closure. setu filed the
# defect on 2026-08-07 (`setu/docs/development/issues/2026-08-07-distlib-deps-sidecar-under-reports.md`,
# still OPEN) and wrote this script rather than wait for it. dhancha had neither, so nothing protected
# its consumers.
#
# ⛔⛔ dhancha's FAILURE MODE IS THE MIRROR OF setu's, AND IT BLOCKED TWO REPOS.
# setu's sidecar UNDER-reports (8 leaves of 12). dhancha's OVER-reports: distlib emitted
# **`kashi_font_data`**, which is not a stdlib leaf at all — kashi is VENDORED
# (`[deps.kashi] modules = ["src/font_data.cyr"]` -> `lib/kashi_font_data.cyr`). `cyrius deps` in a
# consumer then hunts for it in the stdlib and fails outright:
#
#     error: dep dhancha requires 'kashi_font_data' but it is not in the cyrius stdlib
#
# crab and puka could not resolve dhancha at all. ⚠ A consumer supplies a vendored module by declaring
# `[deps.kashi]` ITSELF, which both already did — the sidecar was the only thing wrong.
#
# ⚠ THE DECLARED LIST IS THE TRUTH, and generating from it is what makes both failure directions
# impossible: nothing under-reported (it is the whole array) and nothing invented (a vendored dep is
# not in `[deps] stdlib`, so it cannot appear).
#
# ⛔ Run after `cyrius distlib` — distlib WILL re-add the bad line every time. Diagnosing it from
# scratch cost three wrong answers (a toolchain regression, then lib/ pollution, then dep ordering)
# before the sidecar itself was read.
#
# Run after `cyrius distlib`. CI should run it and fail if it changed anything (see setu's ci.yml:99).
set -eu
cd "$(dirname "$0")/.."

DECLARED=$(python3 - <<'PY'
import re
s = open("cyrius.cyml", encoding="utf-8").read()
# [deps] stdlib = [ ... ] — entries may carry trailing # comments and span lines.
m = re.search(r'^\s*stdlib\s*=\s*\[(.*?)\]', s, re.S | re.M)
if not m:
    raise SystemExit("sync-deps-sidecar: no [deps] stdlib array in cyrius.cyml")
print("\n".join(re.findall(r'"([^"]+)"', m.group(1))))
PY
)

[ -n "$DECLARED" ] || { echo "sync-deps-sidecar: declared stdlib list is empty"; exit 1; }

{
    echo "# cyrius dep sidecar - stdlib leaves this fold requires in scope."
    echo "# Generated by scripts/sync-deps-sidecar.sh from [deps] stdlib in cyrius.cyml."
    echo "# NOT the raw \`cyrius distlib\` output: that emits \`kashi_font_data\`, a VENDORED module and"
    echo "# not a stdlib leaf, which makes \`cyrius deps\` fail in every consumer. See setu's"
    echo "# docs/development/issues/2026-08-07-distlib-deps-sidecar-under-reports.md (same defect, other direction)."
    echo "$DECLARED"
} > dist/dhancha.deps

echo "sync-deps-sidecar: $(echo "$DECLARED" | wc -l | tr -d ' ') leaves written to dist/dhancha.deps"
